name: Validate Code

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci
      - run: npm run lint
      - run: npx tsc --noEmit -p frontend
      - run: npx tsc --noEmit -p backend
