Test this ssh into into ing it
name: Deploy backend to EC2 (publish)

on:
  push:
    branches: [ publish ]
  workflow_dispatch:

env:
  APP_DIR: backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # If your secrets live under an Environment (e.g. Production), add:
    # environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: List backend
        run: ls -la "${{ env.APP_DIR }}"

      # Install deps (use lockfile if present; fallback to npm install)
      - name: Install deps (backend)
        working-directory: ./backend
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            echo "No package-lock.json; using npm install"
            npm install --no-audit --no-fund
          fi

      - name: Build (backend)
        working-directory: ./backend
        run: npm run build

      - name: Verify build output
        working-directory: ./backend
        shell: bash
        run: |
          ls -la dist || true
          test -d dist || { echo "::error::No dist/ folder produced by build"; exit 1; }

      - name: Create deploy.tgz
        shell: bash
        run: |
          FILES="dist package.json"
          [ -f backend/package-lock.json ] && FILES="$FILES package-lock.json"
          [ -f backend/env.production.example ] && FILES="$FILES env.production.example"
          tar -czf deploy.tgz -C backend $FILES
          echo "Tar preview:"; tar -tzf deploy.tgz | sed -n '1,80p'

      # Ensure required secrets exist
      - name: Validate secrets present
        shell: bash
        run: |
          [ -n "${{ secrets.EC2_HOST }}" ]    || { echo "::error::EC2_HOST missing"; exit 1; }
          [ -n "${{ secrets.EC2_USER }}" ]    || { echo "::error::EC2_USER missing"; exit 1; }
          [ -n "${{ secrets.EC2_PATH }}" ]    || { echo "::error::EC2_PATH missing"; exit 1; }
          [ -n "${{ secrets.EC2_KEY_B64 }}" ] || { echo "::error::EC2_KEY_B64 missing"; exit 1; }

      # Decode Base64 key -> step output (avoid file permission issues)
      - name: Decode SSH key
        id: key
        shell: bash
        run: |
          echo "${{ secrets.EC2_KEY_B64 }}" | base64 -d > key.pem
          chmod 600 key.pem
          {
            echo "pem<<EOF"
            cat key.pem
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Probe SSH
        shell: bash
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no -o ConnectTimeout=10 \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'echo EC2_OK $(hostname)'

      - name: Ensure target dir on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ steps.key.outputs.pem }}
          script: |
            set -e
            sudo mkdir -p "${{ secrets.EC2_PATH }}"
            sudo chown -R $USER:$USER "${{ secrets.EC2_PATH }}"
            ls -ld "${{ secrets.EC2_PATH }}"

      - name: Upload to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ steps.key.outputs.pem }}
          source: "deploy.tgz"
          target: "${{ secrets.EC2_PATH }}"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ steps.key.outputs.pem }}
          script: |
            set -e
            cd "${{ secrets.EC2_PATH }}"
            echo "Before extract:" && ls -la
            tar -xzf deploy.tgz && rm -f deploy.tgz
            echo "After extract:" && ls -la

            if [ -f package-lock.json ]; then
              npm ci --omit=dev --no-audit --no-fund
            else
              npm install --omit=dev --no-audit --no-fund
            fi

            # Detect entry from package.json main; fallback to common paths
            ENTRY=$(node -p "try{require('./package.json').main||''}catch(e){''}")
            if [ -z "$ENTRY" ] || [ ! -f "$ENTRY" ]; then
              for f in dist/server.js dist/src/server.js dist/index.js dist/app.js; do
                if [ -f "$f" ]; then ENTRY="$f"; break; fi
              done
            fi
            if [ -z "$ENTRY" ] || [ ! -f "$ENTRY" ]; then
              echo "No entry file found. Dist tree:"; ls -R dist || true; exit 1
            fi
            echo "Using entry file: $ENTRY"

            if command -v pm2 >/dev/null 2>&1; then
              pm2 describe skillin >/dev/null 2>&1 && pm2 reload skillin || pm2 start "$ENTRY" --name skillin
              pm2 save
              pm2 list
            else
              echo "PM2 not found; installing"
              npm i -g pm2
              pm2 start "$ENTRY" --name skillin
              pm2 save
            fi

      - name: Health check (best-effort)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ steps.key.outputs.pem }}
          script: |
            curl -fsS http://127.0.0.1:3000/health || true



      